// Builds js/data/species.js from tools/species.source.mjs.
// For each species it looks up:
//   WoRMS      https://www.marinespecies.org/rest   accepted name, AphiaID, taxonomy
//   OBIS       https://api.obis.org/v3              sighting records + depth histogram
//   Wikipedia  https://en.wikipedia.org/api/rest_v1 summary text + thumbnail
// Run:  node tools/build-species.mjs
// Results are cached in tools/.cache so re-runs are fast and polite to the APIs.

import { SPECIES, LANDMARKS } from './species.source.mjs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const cacheDir = join(here, '.cache');
const UA = 'FathomBuild/1.0 (+https://github.com/ShadowMonarch9099/Fathom)';
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function cached(key, url) {
  const file = join(cacheDir, key.replace(/[^a-z0-9_.-]/gi, '_') + '.json');
  try { return JSON.parse(await readFile(file, 'utf8')); } catch {}
  let data = null;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(url, { headers: { 'User-Agent': UA, 'Accept': 'application/json' } });
      if (res.status === 204 || res.status === 404) { data = null; break; }
      if (!res.ok) throw new Error(res.status + ' ' + url);
      data = await res.json();
      break;
    } catch (e) {
      if (attempt === 2) { console.warn('  ! ' + e.message); return null; }
      await sleep(800 * (attempt + 1));
    }
  }
  await writeFile(file, JSON.stringify(data));
  await sleep(150);
  return data;
}

const trim = (s, n) => {
  if (!s || s.length <= n) return s;
  const cut = s.slice(0, n);
  const end = cut.lastIndexOf('. ');
  return end > n * 0.5 ? cut.slice(0, end + 1) : cut.replace(/\s+\S*$/, '') + '…';
};

function rarityFrom(records) {
  if (records == null) return 'rare';
  if (records >= 50000) return 'common';
  if (records >= 5000) return 'uncommon';
  if (records >= 500) return 'rare';
  return 'legendary';
}

async function enrich(sp) {
  const q = encodeURIComponent(sp.sci);
  const [worms, obis, env, wiki] = await Promise.all([
    cached('worms_' + sp.sci, `https://www.marinespecies.org/rest/AphiaRecordsByName/${q}?like=false&marine_only=false`),
    cached('obis_' + sp.sci, `https://api.obis.org/v3/statistics?scientificname=${q}`),
    cached('obisenv_' + sp.sci, `https://api.obis.org/v3/statistics/env?scientificname=${q}`),
    cached('wiki_' + sp.wiki, `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(sp.wiki)}`),
  ]);
  const w = Array.isArray(worms) ? (worms.find(r => r.status === 'accepted') || worms[0]) : null;
  const records = obis && typeof obis.records === 'number' ? obis.records : null;
  const depthHist = env && Array.isArray(env.depth) ? env.depth.map(b => [b.from, b.records]) : null;
  return {
    ...sp,
    aphiaId: w ? w.valid_AphiaID || w.AphiaID : null,
    acceptedName: w ? w.valid_name || w.scientificname : null,
    rank: w ? w.rank : null,
    taxonomy: w ? [w.phylum, w.class, w.order, w.family].filter(Boolean) : [],
    obisRecords: records,
    depthHist: depthHist && depthHist.some(b => b[1] > 0) ? depthHist : null,
    rarity: sp.rarity || rarityFrom(records),
    summary: wiki && wiki.extract ? trim(wiki.extract, 520) : null,
    image: wiki && wiki.thumbnail ? wiki.thumbnail.source : null,
    wikiUrl: wiki && wiki.content_urls ? wiki.content_urls.desktop.page : `https://en.wikipedia.org/wiki/${sp.wiki}`,
  };
}

await mkdir(cacheDir, { recursive: true });
const ids = new Set();
for (const s of SPECIES) { if (ids.has(s.id)) throw new Error('duplicate id ' + s.id); ids.add(s.id); }

const out = [];
for (const [i, sp] of SPECIES.entries()) {
  process.stdout.write(`[${String(i + 1).padStart(3)}/${SPECIES.length}] ${sp.name}\n`);
  out.push(await enrich(sp));
}

const missing = out.filter(s => !s.summary).map(s => s.name);
const noWorms = out.filter(s => !s.aphiaId).map(s => s.name);
const banner = `// GENERATED by tools/build-species.mjs on ${new Date().toISOString().slice(0, 10)}. Do not edit by hand.
// Sources: WoRMS (marinespecies.org, CC BY 4.0), OBIS (obis.org), Wikipedia (CC BY-SA 4.0).
`;
await mkdir(join(root, 'js', 'data'), { recursive: true });
await writeFile(join(root, 'js', 'data', 'species.js'),
  banner + 'window.FATHOM_SPECIES = ' + JSON.stringify(out) + ';\nwindow.FATHOM_LANDMARKS = ' + JSON.stringify(LANDMARKS) + ';\n');

const tally = out.reduce((a, s) => (a[s.rarity] = (a[s.rarity] || 0) + 1, a), {});
console.log(`\nWrote ${out.length} species. Rarity: ${JSON.stringify(tally)}`);
if (missing.length) console.log('No Wikipedia summary:', missing.join(', '));
if (noWorms.length) console.log('No WoRMS match:', noWorms.join(', '));
