// Curated species list for Fathom.
// Hand-written fields: name, depth placement, habitat, one short fact, pixel-art params.
// tools/build-species.mjs enriches each entry from WoRMS (taxonomy), OBIS (sighting
// records + depth histogram) and Wikipedia (summary, photo) and writes js/data/species.js.
//
// m        typical depth (metres) where the animal spawns during a day dive
// range    [min, max] depth the species is generally reported at
// nightM   depth at night for animals that migrate up after dark
// hab      where it spawns: open | surface | seagrass | reef | kelp | slope | plain | vent | whalefall | trench
// benthic  sits on or near the seafloor
// glow     bioluminescent
// school   how many to draw together
// cm       approximate maximum length in centimetres (drives sprite size)
// art      pixel-art archetype + colours (see js/sprites.js)

export const SPECIES = [
  // ---------------- SUNLIGHT ZONE · surface & open water ----------------
  { id:'man-o-war', name:"Portuguese man o' war", sci:'Physalia physalis', wiki:"Portuguese_man_o'_war", group:'Cnidarian', m:0, range:[0,0], hab:'surface', cm:30, diet:'Small fish',
    fact:'Not one animal but a colony of specialised individuals. A gas-filled float lets it sail on the wind.', art:{t:'jelly', k:'manowar', c1:'#9ad0ff', c2:'#c48bff'} },
  { id:'flying-fish', name:'Flying fish', sci:'Exocoetidae', wiki:'Flying_fish', group:'Fish', m:2, range:[0,20], hab:'surface', cm:35, school:3, diet:'Plankton',
    fact:'Escapes predators by leaping out of the water and gliding on wing-like fins.', art:{t:'fish', c1:'#3d6fa8', c2:'#c9dcef', fin:'wing', tail:'fork'} },
  { id:'sea-sparkle', name:'Sea sparkle', sci:'Noctiluca scintillans', wiki:'Noctiluca_scintillans', group:'Plankton', m:3, range:[0,10], hab:'surface', cm:0.2, school:8, glow:true, diet:'Smaller plankton',
    fact:'A single-celled plankton that glows blue when the water is disturbed, lighting up waves at night.', art:{t:'plankton', k:'dino', c1:'#bfe9ff'} },
  { id:'diatom', name:'Diatoms', sci:'Bacillariophyceae', wiki:'Diatom', group:'Plankton', m:15, range:[0,100], hab:'open', cm:0.1, school:9, diet:'Sunlight (photosynthesis)',
    fact:'These glass-shelled algae produce roughly a fifth of the oxygen made on Earth.', art:{t:'plankton', k:'diatom', c1:'#c7d98a'} },
  { id:'copepod', name:'Copepod', sci:'Calanus finmarchicus', wiki:'Calanus_finmarchicus', group:'Crustacean', m:30, range:[0,200], nightM:10, hab:'open', cm:0.4, school:8, diet:'Phytoplankton',
    fact:'Copepods may be the most numerous animals on Earth, and many fish depend on them for food.', art:{t:'shrimp', k:'copepod', c1:'#e88b4f'} },
  { id:'krill', name:'Antarctic krill', sci:'Euphausia superba', wiki:'Antarctic_krill', group:'Crustacean', m:60, range:[0,200], nightM:15, hab:'open', cm:6, school:9, glow:true, diet:'Phytoplankton',
    fact:'Its swarms make up one of the largest masses of any wild animal, feeding whales, seals and penguins.', art:{t:'shrimp', k:'krill', c1:'#e46a5a'} },
  { id:'sardine', name:'Pacific sardine', sci:'Sardinops sagax', wiki:'Sardinops', group:'Fish', m:20, range:[0,200], hab:'open', cm:30, school:9, diet:'Plankton',
    fact:"Moves in vast schools. The same species makes South Africa's famous 'sardine run' every winter.", art:{t:'fish', c1:'#5f86a6', c2:'#e5edf2', tail:'fork', h:.26} },
  { id:'herring', name:'Atlantic herring', sci:'Clupea harengus', wiki:'Atlantic_herring', group:'Fish', m:60, range:[0,200], nightM:20, hab:'open', cm:40, school:7, diet:'Plankton',
    fact:'Herring make high-pitched sounds by releasing bubbles from their rear end, possibly to keep the school together at night.', art:{t:'fish', c1:'#4e7590', c2:'#dfe8ee', tail:'fork', h:.26} },
  { id:'mahi', name:'Mahi-mahi', sci:'Coryphaena hippurus', wiki:'Mahi-mahi', group:'Fish', m:15, range:[0,85], hab:'open', cm:150, diet:'Fish & squid',
    fact:'One of the fastest-growing fish. Its gold, green and blue colours can flash and change within seconds.', art:{t:'fish', c1:'#3fa36b', c2:'#e9cf46', head:'blunt', fin:'long', tail:'fork', h:.3} },
  { id:'sailfish', name:'Indo-Pacific sailfish', sci:'Istiophorus platypterus', wiki:'Sailfish', group:'Fish', m:20, range:[0,200], hab:'open', cm:340, diet:'Sardines & squid',
    fact:'Raises its huge sail-like fin to herd schools of sardines, then slashes at them with its bill.', art:{t:'fish', c1:'#264f86', c2:'#c5d4e4', fin:'sail', bill:true, tail:'lunate', h:.2} },
  { id:'barracuda', name:'Great barracuda', sci:'Sphyraena barracuda', wiki:'Great_barracuda', group:'Fish', m:25, range:[0,100], hab:'open', cm:200, diet:'Fish',
    fact:'An ambush hunter that strikes with sudden bursts of speed and fang-like teeth.', art:{t:'fish', c1:'#6c8796', c2:'#dde6ea', pattern:'bars', teeth:true, tail:'fork', h:.17} },
  { id:'bluefin', name:'Atlantic bluefin tuna', sci:'Thunnus thynnus', wiki:'Atlantic_bluefin_tuna', group:'Fish', m:100, range:[0,1000], hab:'open', cm:300, diet:'Fish & squid',
    fact:'Keeps its muscles warmer than the surrounding water and can cross the entire Atlantic Ocean.', art:{t:'fish', c1:'#1f3a5e', c2:'#cfd8de', tail:'lunate', finlets:true, h:.3} },
  { id:'mola', name:'Ocean sunfish', sci:'Mola mola', wiki:'Ocean_sunfish', group:'Fish', m:60, range:[0,600], hab:'open', cm:330, diet:'Jellyfish',
    fact:'One of the heaviest bony fish. A single female can carry around 300 million eggs.', art:{t:'mola', c1:'#8c9ba3', c2:'#c9d2d6'} },
  { id:'whale-shark', name:'Whale shark', sci:'Rhincodon typus', wiki:'Whale_shark', group:'Shark & ray', m:40, range:[0,1900], hab:'open', cm:1800, diet:'Plankton & small fish',
    fact:'The largest fish in the sea, yet it feeds by filtering plankton and small fish from the water.', art:{t:'shark', k:'whale', c1:'#3e5566', c2:'#c7d1d6', spots:true} },
  { id:'basking-shark', name:'Basking shark', sci:'Cetorhinus maximus', wiki:'Basking_shark', group:'Shark & ray', m:15, range:[0,900], hab:'open', cm:1000, diet:'Plankton',
    fact:'The second-largest fish. It cruises with its huge mouth wide open, filtering plankton.', art:{t:'shark', k:'basking', c1:'#4d5459', c2:'#8f979b'} },
  { id:'great-white', name:'Great white shark', sci:'Carcharodon carcharias', wiki:'Great_white_shark', group:'Shark & ray', m:60, range:[0,1200], hab:'open', cm:600, diet:'Seals, fish & whales',
    fact:'Senses the tiny electric fields of living prey through jelly-filled pores on its snout.', art:{t:'shark', c1:'#59646c', c2:'#eef1f2'} },
  { id:'tiger-shark', name:'Tiger shark', sci:'Galeocerdo cuvier', wiki:'Tiger_shark', group:'Shark & ray', m:40, range:[0,350], hab:'open', cm:550, diet:'Almost anything',
    fact:'Famous for eating almost anything, from sea turtles and seabirds to tyres and licence plates.', art:{t:'shark', c1:'#6b6a58', c2:'#d8d6c6', pattern:'bars'} },
  { id:'hammerhead', name:'Scalloped hammerhead', sci:'Sphyrna lewini', wiki:'Scalloped_hammerhead', group:'Shark & ray', m:80, range:[0,500], hab:'open', cm:430, school:3, diet:'Fish & squid',
    fact:'Its wide head spreads out its senses. By day these sharks often gather in large schools.', art:{t:'shark', k:'hammer', c1:'#69767d', c2:'#e2e7ea'} },
  { id:'manta', name:'Giant oceanic manta ray', sci:'Mobula birostris', wiki:'Giant_oceanic_manta_ray', group:'Shark & ray', m:30, range:[0,1000], hab:'open', cm:700, diet:'Zooplankton',
    fact:'Has one of the largest brains for its body of any fish and can measure about 7 m from wingtip to wingtip.', art:{t:'ray', k:'manta', c1:'#20262b', c2:'#e6ecef'} },
  { id:'eagle-ray', name:'Spotted eagle ray', sci:'Aetobatus narinari', wiki:'Spotted_eagle_ray', group:'Shark & ray', m:20, range:[1,80], hab:'reef', cm:500, diet:'Clams & snails',
    fact:'Digs clams and snails out of the sand with its shovel-shaped snout.', art:{t:'ray', c1:'#2c3a4a', c2:'#f2f4f5', spots:true} },
  { id:'moon-jelly', name:'Moon jellyfish', sci:'Aurelia aurita', wiki:'Aurelia_aurita', group:'Cnidarian', m:12, range:[0,200], hab:'open', cm:40, diet:'Plankton',
    fact:'Has no brain, heart or bones, and its body is about 95% water.', art:{t:'jelly', k:'moon', c1:'#cfe0ff'} },
  { id:'lions-mane', name:"Lion's mane jellyfish", sci:'Cyanea capillata', wiki:"Lion's_mane_jellyfish", group:'Cnidarian', m:25, range:[0,200], hab:'open', cm:200, diet:'Fish, plankton & jellies',
    fact:'One of the largest jellyfish. Its tentacles can trail more than 30 m behind it.', art:{t:'jelly', k:'lion', c1:'#d8663e', c2:'#f1b27a'} },
  { id:'box-jelly', name:'Australian box jellyfish', sci:'Chironex fleckeri', wiki:'Chironex_fleckeri', group:'Cnidarian', m:6, range:[0,20], hab:'seagrass', cm:30, diet:'Shrimp & small fish',
    fact:'Has 24 eyes, and some of them can form images.', art:{t:'jelly', k:'box', c1:'#d6f0f5'} },
  { id:'comb-jelly', name:'Warty comb jelly', sci:'Mnemiopsis leidyi', wiki:'Mnemiopsis', group:'Comb jelly', m:20, range:[0,100], hab:'open', cm:12, glow:true, diet:'Zooplankton',
    fact:'Swims by beating rows of tiny hairs that scatter light into shimmering rainbows.', art:{t:'comb', c1:'#d9f4ff'} },
  { id:'sea-angel', name:'Sea angel', sci:'Clione limacina', wiki:'Clione_limacina', group:'Mollusc', m:80, range:[0,500], hab:'open', cm:4, diet:'Sea butterflies',
    fact:'A shell-less swimming snail that hunts sea butterflies.', art:{t:'snail', k:'angel', c1:'#f1d6e4', c2:'#ff8a5c'} },
  { id:'sea-butterfly', name:'Sea butterfly', sci:'Limacina helicina', wiki:'Limacina_helicina', group:'Mollusc', m:90, range:[0,500], hab:'open', cm:1, school:5, diet:'Plankton',
    fact:'Its thin shell dissolves in more acidic water, making it an early warning sign of ocean acidification.', art:{t:'snail', k:'butterfly', c1:'#c9b48d'} },
  { id:'salp', name:'Salp', sci:'Salpidae', wiki:'Salp', group:'Tunicate', m:150, range:[0,800], hab:'open', cm:30, diet:'Phytoplankton',
    fact:'Jets along by pumping water through its body. Its droppings sink fast, carrying carbon to the deep sea.', art:{t:'salp', c1:'#dff3ff'} },

  // marine mammals, reptiles, birds
  { id:'blue-whale', name:'Blue whale', sci:'Balaenoptera musculus', wiki:'Blue_whale', group:'Mammal', m:60, range:[0,500], hab:'open', cm:3000, diet:'Krill',
    fact:'The largest animal known to have ever lived, and it feeds almost entirely on tiny krill.', art:{t:'whale', k:'baleen', c1:'#5b7389', c2:'#93a8b8'} },
  { id:'humpback', name:'Humpback whale', sci:'Megaptera novaeangliae', wiki:'Humpback_whale', group:'Mammal', m:35, range:[0,600], hab:'open', cm:1600, diet:'Krill & small fish',
    fact:'Males sing long, complex songs that travel for kilometres underwater and change from year to year.', art:{t:'whale', k:'humpback', c1:'#2f3a44', c2:'#d9dfe3'} },
  { id:'orca', name:'Orca', sci:'Orcinus orca', wiki:'Orca', group:'Mammal', m:30, range:[0,1000], hab:'open', cm:900, diet:'Fish, seals & whales',
    fact:'The largest member of the dolphin family. Each pod has its own dialect of calls.', art:{t:'whale', k:'orca', c1:'#121618', c2:'#f4f6f7'} },
  { id:'bottlenose', name:'Common bottlenose dolphin', sci:'Tursiops truncatus', wiki:'Common_bottlenose_dolphin', group:'Mammal', m:20, range:[0,500], hab:'open', cm:400, school:3, diet:'Fish & squid',
    fact:'Finds food by echolocation. Each dolphin has a signature whistle that works like a name.', art:{t:'whale', k:'dolphin', c1:'#7c8f9d', c2:'#d6dee3'} },
  { id:'sperm-whale', name:'Sperm whale', sci:'Physeter macrocephalus', wiki:'Sperm_whale', group:'Mammal', m:900, range:[0,2250], hab:'open', cm:1800, diet:'Squid',
    fact:'The largest predator with teeth. It dives past 1,000 m to hunt squid and can hold its breath for over an hour.', art:{t:'whale', k:'sperm', c1:'#4b545c', c2:'#7d868d'} },
  { id:'narwhal', name:'Narwhal', sci:'Monodon monoceros', wiki:'Narwhal', group:'Mammal', m:700, range:[0,1800], hab:'open', cm:550, diet:'Fish & squid',
    fact:'Its spiral tusk is a long tooth packed with nerve endings. Narwhals dive deeper than 1,500 m.', art:{t:'whale', k:'narwhal', c1:'#8a8f8f', c2:'#d8dad5'} },
  { id:'beaked-whale', name:"Cuvier's beaked whale", sci:'Ziphius cavirostris', wiki:"Cuvier's_beaked_whale", group:'Mammal', m:1900, range:[0,3000], hab:'open', cm:700, diet:'Deep-sea squid',
    fact:'Holds the records for the deepest and longest mammal dives: almost 3,000 m and over 3½ hours.', art:{t:'whale', k:'beaked', c1:'#7a6a5c', c2:'#cbbfb1'} },
  { id:'elephant-seal', name:'Northern elephant seal', sci:'Mirounga angustirostris', wiki:'Northern_elephant_seal', group:'Mammal', m:500, range:[0,1500], hab:'open', cm:500, diet:'Squid & fish',
    fact:'Can dive deeper than 1,500 m and spends most of its life underwater, surfacing only briefly to breathe.', art:{t:'seal', c1:'#6c5f55', c2:'#a39282'} },
  { id:'sea-otter', name:'Sea otter', sci:'Enhydra lutris', wiki:'Sea_otter', group:'Mammal', m:2, range:[0,40], hab:'kelp', cm:150, diet:'Urchins, crabs & clams',
    fact:'Has the densest fur of any animal and uses rocks as tools to crack open shellfish.', art:{t:'otter', c1:'#5b4434', c2:'#c7b29a'} },
  { id:'dugong', name:'Dugong', sci:'Dugong dugon', wiki:'Dugong', group:'Mammal', m:6, range:[1,20], hab:'seagrass', cm:400, diet:'Seagrass',
    fact:'A seagrass-grazing mammal more closely related to elephants than to whales.', art:{t:'whale', k:'dugong', c1:'#9a8f86', c2:'#c9c0b8'} },
  { id:'emperor-penguin', name:'Emperor penguin', sci:'Aptenodytes forsteri', wiki:'Emperor_penguin', group:'Bird', m:250, range:[0,565], hab:'open', cm:120, diet:'Fish, krill & squid',
    fact:'Dives deeper than any other bird, beyond 500 m, holding its breath for over 20 minutes.', art:{t:'penguin', c1:'#1c2329', c2:'#f3f3ee', c3:'#f2b84b'} },
  { id:'leatherback', name:'Leatherback sea turtle', sci:'Dermochelys coriacea', wiki:'Leatherback_sea_turtle', group:'Reptile', m:120, range:[0,1280], hab:'open', cm:220, diet:'Jellyfish',
    fact:'The largest living turtle. It feeds on jellyfish and can dive deeper than 1,000 m.', art:{t:'turtle', k:'leather', c1:'#2b3238', c2:'#8b979e'} },
  { id:'green-turtle', name:'Green sea turtle', sci:'Chelonia mydas', wiki:'Green_sea_turtle', group:'Reptile', m:8, range:[0,40], hab:'seagrass', cm:150, diet:'Seagrass & algae',
    fact:'Adults are mostly vegetarian, grazing on seagrass and algae.', art:{t:'turtle', c1:'#6c7f45', c2:'#a9b77a'} },
  { id:'hawksbill', name:'Hawksbill sea turtle', sci:'Eretmochelys imbricata', wiki:'Hawksbill_sea_turtle', group:'Reptile', m:14, range:[0,50], hab:'reef', cm:110, diet:'Sponges',
    fact:'One of the few animals that eats sponges, which helps corals compete for space on the reef.', art:{t:'turtle', c1:'#8a5a2e', c2:'#d8b27a', pattern:'mottle'} },
  { id:'sea-snake', name:'Olive sea snake', sci:'Aipysurus laevis', wiki:'Olive_sea_snake', group:'Reptile', m:18, range:[0,45], hab:'reef', cm:200, diet:'Fish & eggs',
    fact:'Can sense light with its tail, which helps it keep its whole body hidden in coral.', art:{t:'snake', c1:'#8b7c45', c2:'#c7b878'} },

  // ---------------- SUNLIGHT ZONE · seagrass, coral reef, kelp ----------------
  { id:'seahorse', name:'Seahorse', sci:'Hippocampus', wiki:'Seahorse', group:'Fish', m:5, range:[1,30], hab:'seagrass', benthic:true, cm:20, diet:'Tiny shrimp',
    fact:'The male becomes pregnant and gives birth to the young.', art:{t:'seahorse', c1:'#e2a33b'} },
  { id:'seadragon', name:'Leafy seadragon', sci:'Phycodurus eques', wiki:'Leafy_seadragon', group:'Fish', m:30, range:[4,50], hab:'kelp', cm:35, diet:'Mysid shrimp',
    fact:'Leaf-like flaps camouflage it as drifting seaweed, and the male carries the eggs.', art:{t:'seahorse', k:'dragon', c1:'#c9a23a', c2:'#7f9b3a'} },
  { id:'clownfish', name:'Ocellaris clownfish', sci:'Amphiprion ocellaris', wiki:'Ocellaris_clownfish', group:'Fish', m:10, range:[1,15], hab:'reef', cm:11, school:2, diet:'Algae & plankton',
    fact:'Lives safely among stinging anemone tentacles. All are born male, and the largest can become female.', art:{t:'fish', c1:'#f07a1f', c2:'#f07a1f', pattern:'clown', tail:'round', h:.42} },
  { id:'anemone', name:'Magnificent sea anemone', sci:'Heteractis magnifica', wiki:'Heteractis_magnifica', group:'Cnidarian', m:10, range:[1,20], hab:'reef', benthic:true, cm:50, diet:'Plankton & small fish',
    fact:'Fires microscopic stinging cells, yet shelters clownfish that help defend and clean it.', art:{t:'anemone', c1:'#c45b8f', c2:'#f0d7a0'} },
  { id:'staghorn', name:'Staghorn coral', sci:'Acropora cervicornis', wiki:'Staghorn_coral', group:'Cnidarian', m:9, range:[0,30], hab:'reef', benthic:true, cm:150, diet:'Sunlight via algae, plankton',
    fact:'Its branches are covered in tiny animals called polyps that host algae, which feed the coral using sunlight.', art:{t:'coral', k:'stag', c1:'#d7b36b', c2:'#f2deaa'} },
  { id:'brain-coral', name:'Grooved brain coral', sci:'Diploria labyrinthiformis', wiki:'Diploria_labyrinthiformis', group:'Cnidarian', m:12, range:[1,40], hab:'reef', benthic:true, cm:180, diet:'Sunlight via algae, plankton',
    fact:'Grows slowly into a maze-patterned dome. Large colonies can be centuries old.', art:{t:'coral', k:'brain', c1:'#b5a35a', c2:'#7a6c3a'} },
  { id:'giant-clam', name:'Giant clam', sci:'Tridacna gigas', wiki:'Giant_clam', group:'Mollusc', m:11, range:[1,20], hab:'reef', benthic:true, cm:120, diet:'Sunlight via algae, plankton',
    fact:'The largest clam in the world. It can weigh over 200 kg and farms algae in its colourful mantle.', art:{t:'clam', c1:'#c9c3b1', c2:'#3aa7a0'} },
  { id:'christmas-worm', name:'Christmas tree worm', sci:'Spirobranchus giganteus', wiki:'Spirobranchus_giganteus', group:'Worm', m:8, range:[1,30], hab:'reef', benthic:true, cm:4, school:3, diet:'Plankton',
    fact:'Catches food with spiral plumes that vanish into its tube in a blink if disturbed.', art:{t:'worm', k:'xmas', c1:'#3f8fe0', c2:'#f0c03a'} },
  { id:'parrotfish', name:'Bumphead parrotfish', sci:'Bolbometopon muricatum', wiki:'Green_humphead_parrotfish', group:'Fish', m:12, range:[1,30], hab:'reef', cm:130, diet:'Coral & algae',
    fact:'Bites and grinds coral. The fine sand it excretes helps build white tropical beaches.', art:{t:'fish', c1:'#3e7d6d', c2:'#9bc7a7', head:'bump', tail:'round', h:.42} },
  { id:'blue-tang', name:'Blue tang', sci:'Paracanthurus hepatus', wiki:'Paracanthurus', group:'Fish', m:9, range:[2,40], hab:'reef', cm:30, school:3, diet:'Plankton & algae',
    fact:'Carries a scalpel-sharp spine near its tail for defence.', art:{t:'fish', c1:'#2a5fd6', c2:'#f2d23a', pattern:'tang', tail:'fork', h:.48} },
  { id:'moorish-idol', name:'Moorish idol', sci:'Zanclus cornutus', wiki:'Moorish_idol', group:'Fish', m:15, range:[3,180], hab:'reef', cm:23, diet:'Sponges & algae',
    fact:'The only living member of its family, known for its long, trailing dorsal fin.', art:{t:'fish', c1:'#f2e6b8', c2:'#f2e6b8', pattern:'idol', fin:'streamer', tail:'fork', h:.7} },
  { id:'mandarinfish', name:'Mandarinfish', sci:'Synchiropus splendidus', wiki:'Synchiropus_splendidus', group:'Fish', m:6, range:[1,18], hab:'reef', benthic:true, cm:6, diet:'Tiny crustaceans',
    fact:'One of very few animals whose blue colour comes from blue pigment in its cells rather than light tricks.', art:{t:'fish', c1:'#2b5fd0', c2:'#f08a2a', pattern:'swirl', tail:'round', h:.38} },
  { id:'cleaner-wrasse', name:'Bluestreak cleaner wrasse', sci:'Labroides dimidiatus', wiki:'Bluestreak_cleaner_wrasse', group:'Fish', m:10, range:[1,40], hab:'reef', cm:14, diet:'Parasites on other fish',
    fact:"Runs 'cleaning stations' where larger fish line up to have parasites picked off.", art:{t:'fish', c1:'#7fb7e8', c2:'#e8f1f7', pattern:'stripe', tail:'round', h:.25} },
  { id:'humphead-wrasse', name:'Humphead wrasse', sci:'Cheilinus undulatus', wiki:'Humphead_wrasse', group:'Fish', m:20, range:[1,100], hab:'reef', cm:200, diet:'Molluscs, fish & starfish',
    fact:'Can grow to 2 m. Most start life female and some later change to male.', art:{t:'fish', c1:'#3f8a7c', c2:'#86c2a6', head:'bump', tail:'round', h:.45} },
  { id:'cots', name:'Crown-of-thorns starfish', sci:'Acanthaster planci', wiki:'Crown-of-thorns_starfish', group:'Echinoderm', m:12, range:[1,30], hab:'reef', benthic:true, cm:35, diet:'Living coral',
    fact:'Feeds on living coral, and population outbreaks can strip large areas of reef.', art:{t:'star', k:'crown', c1:'#b04a5a', c2:'#e6a0a8'} },
  { id:'octopus', name:'Common octopus', sci:'Octopus vulgaris', wiki:'Common_octopus', group:'Mollusc', m:20, range:[0,200], hab:'reef', benthic:true, cm:130, diet:'Crabs & clams',
    fact:'Has three hearts and blue blood, and can change its colour and skin texture in an instant.', art:{t:'octopus', c1:'#b8653d', c2:'#e0a07a'} },
  { id:'mimic-octopus', name:'Mimic octopus', sci:'Thaumoctopus mimicus', wiki:'Mimic_octopus', group:'Mollusc', m:12, range:[2,37], hab:'reef', benthic:true, cm:60, diet:'Small fish & crabs',
    fact:'Impersonates dangerous animals such as lionfish and sea snakes to scare off predators.', art:{t:'octopus', c1:'#c9a07a', c2:'#3b2a22', pattern:'bands'} },
  { id:'cuttlefish', name:'Common cuttlefish', sci:'Sepia officinalis', wiki:'Common_cuttlefish', group:'Mollusc', m:25, range:[0,200], hab:'reef', cm:45, diet:'Crabs & fish',
    fact:'Changes colour with millions of skin cells, even though it is thought to be colour-blind.', art:{t:'squid', k:'cuttle', c1:'#b3946a', c2:'#e5d2b0'} },
  { id:'mantis-shrimp', name:'Peacock mantis shrimp', sci:'Odontodactylus scyllarus', wiki:'Odontodactylus_scyllarus', group:'Crustacean', m:15, range:[3,40], hab:'reef', benthic:true, cm:18, diet:'Snails & crabs',
    fact:'Strikes with a club so fast that the water around it boils into collapsing bubbles.', art:{t:'shrimp', k:'mantis', c1:'#2eae6a', c2:'#f05a3a'} },
  { id:'pistol-shrimp', name:'Pistol shrimp', sci:'Alpheidae', wiki:'Alpheidae', group:'Crustacean', m:10, range:[0,50], hab:'reef', benthic:true, cm:5, diet:'Small fish & worms',
    fact:'Snaps its claw shut so fast it makes one of the loudest sounds in the ocean.', art:{t:'shrimp', k:'pistol', c1:'#d9824f'} },
  { id:'spiny-lobster', name:'Caribbean spiny lobster', sci:'Panulirus argus', wiki:'Caribbean_spiny_lobster', group:'Crustacean', m:30, range:[0,90], hab:'kelp', benthic:true, cm:60, diet:'Snails, clams & crabs',
    fact:'Migrates across the seafloor in long single-file lines, each lobster touching the one ahead.', art:{t:'shrimp', k:'lobster', c1:'#a25a33', c2:'#e5c08a'} },
  { id:'lionfish', name:'Red lionfish', sci:'Pterois volitans', wiki:'Red_lionfish', group:'Fish', m:20, range:[2,300], hab:'reef', cm:47, diet:'Small fish & shrimp',
    fact:'Its spines carry venom. In the Atlantic, where it was introduced, it has become an invasive predator.', art:{t:'fish', c1:'#c4473a', c2:'#f3e2cf', pattern:'bars', fin:'spines', tail:'round', h:.36} },
  { id:'stonefish', name:'Reef stonefish', sci:'Synanceia verrucosa', wiki:'Reef_stonefish', group:'Fish', m:6, range:[0,30], hab:'reef', benthic:true, cm:40, diet:'Small fish & shrimp',
    fact:'Considered the most venomous fish, and camouflaged to look exactly like a rock.', art:{t:'fish', c1:'#6e6458', c2:'#9b8f7e', pattern:'mottle', tail:'round', h:.48} },
  { id:'moray', name:'Giant moray', sci:'Gymnothorax javanicus', wiki:'Giant_moray', group:'Fish', m:20, range:[0,50], hab:'reef', benthic:true, cm:300, diet:'Fish & octopus',
    fact:'Has a second set of jaws in its throat that shoot forward to pull prey in.', art:{t:'eel', k:'moray', c1:'#6f6a3a', c2:'#b9b07a'} },
  { id:'whitetip', name:'Whitetip reef shark', sci:'Triaenodon obesus', wiki:'Whitetip_reef_shark', group:'Shark & ray', m:22, range:[1,330], hab:'reef', cm:160, diet:'Reef fish & octopus',
    fact:'Unlike many sharks, it can rest motionless on the seabed, often tucked inside caves.', art:{t:'shark', c1:'#7d8a8f', c2:'#e6eaec', tips:true} },
  { id:'spanish-dancer', name:'Spanish dancer', sci:'Hexabranchus sanguineus', wiki:'Hexabranchus_sanguineus', group:'Mollusc', m:14, range:[1,50], hab:'reef', cm:40, diet:'Sponges',
    fact:"A large sea slug that swims by flexing its frilly red body like a dancer's skirt.", art:{t:'snail', k:'dancer', c1:'#d23a3a', c2:'#f39a8a'} },
  { id:'puffer-artist', name:'White-spotted pufferfish', sci:'Torquigener albomaculosus', wiki:'Torquigener_albomaculosus', group:'Fish', m:25, range:[10,27], hab:'reef', benthic:true, cm:12, diet:'Small invertebrates',
    fact:'Males sculpt circular patterns about 2 m wide in the sand to attract females.', art:{t:'fish', c1:'#b8a98a', c2:'#efe7d6', pattern:'spots', tail:'round', h:.42} },
  { id:'flounder', name:'Peacock flounder', sci:'Bothus lunatus', wiki:'Peacock_flounder', group:'Fish', m:18, range:[1,100], hab:'reef', benthic:true, cm:45, diet:'Small fish & crabs',
    fact:'Both eyes sit on one side of its flat body, and it changes colour to match the seabed.', art:{t:'fish', k:'flat', c1:'#9a8a6c', c2:'#7fb7d8', pattern:'spots', h:.18} },
  { id:'garibaldi', name:'Garibaldi', sci:'Hypsypops rubicundus', wiki:'Garibaldi_(fish)', group:'Fish', m:10, range:[0,30], hab:'kelp', cm:30, diet:'Sponges & worms',
    fact:'Males clear a patch of red algae and guard it as a nest for the eggs.', art:{t:'fish', c1:'#f26a1b', c2:'#f9a04a', tail:'fork', h:.48} },
  { id:'giant-kelp', name:'Giant kelp', sci:'Macrocystis pyrifera', wiki:'Macrocystis_pyrifera', group:'Alga', m:40, range:[2,40], hab:'kelp', benthic:true, cm:300, diet:'Sunlight (photosynthesis)',
    fact:'One of the fastest-growing organisms on Earth, adding up to about 60 cm in a day.', art:{t:'kelp', c1:'#7a6a1f', c2:'#a58f2c'} },
  { id:'purple-urchin', name:'Purple sea urchin', sci:'Strongylocentrotus purpuratus', wiki:'Strongylocentrotus_purpuratus', group:'Echinoderm', m:20, range:[0,90], hab:'kelp', benthic:true, cm:10, school:3, diet:'Kelp',
    fact:"Without predators such as sea otters, urchins can graze kelp forests into bare 'urchin barrens'.", art:{t:'urchin', c1:'#6a3a8a'} },
  { id:'cod', name:'Atlantic cod', sci:'Gadus morhua', wiki:'Atlantic_cod', group:'Fish', m:110, range:[0,600], hab:'open', cm:200, school:3, diet:'Fish & crustaceans',
    fact:"Overfishing collapsed Canada's cod fishery in 1992, and some stocks have still not fully recovered.", art:{t:'fish', c1:'#8b8360', c2:'#e5dfc8', pattern:'spots', barbel:true, tail:'round', h:.26} },

  // ---------------- TWILIGHT ZONE ----------------
  { id:'coelacanth', name:'West Indian Ocean coelacanth', sci:'Latimeria chalumnae', wiki:'West_Indian_Ocean_coelacanth', group:'Fish', m:220, range:[100,500], hab:'slope', cm:200, diet:'Fish & squid',
    fact:'Thought to have died out with the dinosaurs until one was caught off South Africa in 1938.', art:{t:'fish', c1:'#2f4a6a', c2:'#7f9dbb', pattern:'spots', fin:'lobed', tail:'coel', h:.3} },
  { id:'nautilus', name:'Chambered nautilus', sci:'Nautilus pompilius', wiki:'Chambered_nautilus', group:'Mollusc', m:350, range:[0,700], nightM:120, hab:'slope', cm:25, diet:'Shrimp, crabs & carrion',
    fact:'Adjusts gas and liquid in its chambered shell to rise and sink, a design that has lasted for millions of years.', art:{t:'nautilus', c1:'#f2e8d8', c2:'#a5502e'} },
  { id:'spider-crab', name:'Japanese spider crab', sci:'Macrocheira kaempferi', wiki:'Japanese_spider_crab', group:'Crustacean', m:300, range:[50,600], hab:'slope', benthic:true, cm:370, diet:'Carrion & shellfish',
    fact:'Has the longest legs of any arthropod, spanning up to about 3.7 m.', art:{t:'crab', k:'spider', c1:'#d0763f', c2:'#f2cfa0'} },
  { id:'ratfish', name:'Spotted ratfish', sci:'Hydrolagus colliei', wiki:'Spotted_ratfish', group:'Fish', m:250, range:[0,1000], hab:'slope', benthic:true, cm:97, diet:'Clams, crabs & worms',
    fact:'A ghostly cousin of sharks, with a venomous spine in front of its dorsal fin.', art:{t:'fish', c1:'#8a7d86', c2:'#cfc6cc', pattern:'spots', tail:'rat', eye:1.6, h:.28} },
  { id:'deep-coral', name:'Cold-water coral', sci:'Desmophyllum pertusum', wiki:'Lophelia_pertusa', group:'Cnidarian', m:500, range:[200,1000], hab:'slope', benthic:true, cm:200, diet:'Drifting plankton',
    fact:'Builds reefs in cold, dark water with no sunlight at all, feeding on drifting plankton.', art:{t:'coral', k:'deep', c1:'#e8e2d6', c2:'#f0a0a0'} },
  { id:'hagfish', name:'Pacific hagfish', sci:'Eptatretus stoutii', wiki:'Pacific_hagfish', group:'Fish', m:600, range:[15,970], hab:'slope', benthic:true, cm:60, diet:'Carrion & worms',
    fact:'When grabbed, it releases enough slime to fill a bucket in seconds.', art:{t:'eel', k:'hag', c1:'#b58a8f', c2:'#d8b9bc'} },
  { id:'venus-basket', name:"Venus' flower basket", sci:'Euplectella aspergillum', wiki:"Venus'_flower_basket", group:'Sponge', m:750, range:[100,1000], hab:'slope', benthic:true, cm:30, diet:'Bacteria & plankton',
    fact:'A glass sponge. A pair of shrimp often move in when young and grow too big to ever leave.', art:{t:'sponge', k:'venus', c1:'#e6e2cf'} },
  { id:'blobfish', name:'Blobfish', sci:'Psychrolutes marcidus', wiki:'Psychrolutes_marcidus', group:'Fish', m:900, range:[600,1200], hab:'slope', benthic:true, cm:30, diet:'Crabs & sea urchins',
    fact:"Looks like a normal fish at depth. It only sags into a 'blob' when hauled up to the surface.", art:{t:'fish', k:'blob', c1:'#d9a4a0', c2:'#efcfcc', tail:'rat', h:.45} },
  { id:'lanternfish', name:'Lanternfish', sci:'Myctophidae', wiki:'Lanternfish', group:'Fish', m:450, range:[0,1500], nightM:40, hab:'open', cm:15, school:7, glow:true, diet:'Zooplankton',
    fact:'Each night many rise toward the surface to feed and sink at dawn, part of the largest daily migration on Earth.', art:{t:'fish', c1:'#4f5f6c', c2:'#9fb0bc', photo:'row', tail:'fork', eye:1.5, h:.28} },
  { id:'bristlemouth', name:'Bristlemouth', sci:'Cyclothone', wiki:'Cyclothone', group:'Fish', m:650, range:[300,2500], hab:'open', cm:7, school:6, glow:true, diet:'Copepods',
    fact:'Possibly the most abundant vertebrate on Earth, numbering in the hundreds of trillions.', art:{t:'fish', c1:'#2d2a2f', c2:'#4c4650', photo:'row', teeth:true, tail:'fork', h:.18} },
  { id:'hatchetfish', name:'Silver hatchetfish', sci:'Argyropelecus aculeatus', wiki:'Argyropelecus_aculeatus', group:'Fish', m:450, range:[100,600], nightM:150, hab:'open', cm:8, school:4, glow:true, diet:'Zooplankton',
    fact:'Belly lights match the faint glow from above, hiding its silhouette from hunters below.', art:{t:'fish', k:'hatchet', c1:'#c6d3dc', c2:'#8ea3b2', photo:'belly'} },
  { id:'humboldt', name:'Humboldt squid', sci:'Dosidicus gigas', wiki:'Humboldt_squid', group:'Mollusc', m:400, range:[0,1200], nightM:80, hab:'open', cm:150, school:3, glow:true, diet:'Fish & squid',
    fact:'Hunts in groups and can flash its skin from red to white in a fraction of a second.', art:{t:'squid', c1:'#b8402f', c2:'#f0c4b0'} },
  { id:'firefly-squid', name:'Firefly squid', sci:'Watasenia scintillans', wiki:'Firefly_squid', group:'Mollusc', m:350, range:[0,600], nightM:30, hab:'open', cm:8, school:5, glow:true, diet:'Small fish & shrimp',
    fact:"Covered in light organs. Each spring millions gather in Japan's Toyama Bay, lighting up the shore.", art:{t:'squid', k:'firefly', c1:'#5a4a8a', c2:'#9a8ac8'} },
  { id:'glass-squid', name:'Glass squid', sci:'Cranchiidae', wiki:'Cranchiidae', group:'Mollusc', m:500, range:[0,2000], hab:'open', cm:30, glow:true, diet:'Plankton & small animals',
    fact:'Almost completely transparent, it hides in open water where there is nothing else to hide behind.', art:{t:'squid', k:'glass', c1:'#d6eef6', clear:true} },
  { id:'cockeyed-squid', name:'Cock-eyed squid', sci:'Histioteuthis heteropsis', wiki:'Histioteuthis_heteropsis', group:'Mollusc', m:600, range:[200,1000], hab:'open', cm:20, glow:true, diet:'Shrimp & small fish',
    fact:'One huge eye looks up for silhouettes while a small eye looks down for glowing animals.', art:{t:'squid', k:'cockeye', c1:'#a8323a', c2:'#e48a8a'} },
  { id:'giant-squid', name:'Giant squid', sci:'Architeuthis dux', wiki:'Giant_squid', group:'Mollusc', m:700, range:[300,1000], hab:'open', cm:1300, diet:'Fish & squid',
    fact:'Has eyes as big as dinner plates, among the largest in the animal kingdom.', art:{t:'squid', k:'giant', c1:'#b5523d', c2:'#e5a080'} },
  { id:'vampire-squid', name:'Vampire squid', sci:'Vampyroteuthis infernalis', wiki:'Vampire_squid', group:'Mollusc', m:750, range:[600,1200], hab:'open', cm:30, glow:true, diet:'Marine snow',
    fact:'Despite its name it eats marine snow, the bits of dead matter that drift down from above.', art:{t:'squid', k:'vampire', c1:'#5c1a24', c2:'#8a3a44'} },
  { id:'glass-octopus', name:'Glass octopus', sci:'Vitreledonella richardi', wiki:'Vitreledonella', group:'Mollusc', m:800, range:[200,2000], hab:'open', cm:45, diet:'Small crustaceans',
    fact:'So transparent that only its eyes, optic nerves and digestive gland are easy to see.', art:{t:'octopus', k:'glass', c1:'#dceff6', clear:true} },
  { id:'telescope-octopus', name:'Telescope octopus', sci:'Amphitretus pelagicus', wiki:'Amphitretus', group:'Mollusc', m:900, range:[100,2000], hab:'open', cm:9, diet:'Small crustaceans',
    fact:'A see-through octopus whose tube-shaped eyes point upward like a pair of telescopes.', art:{t:'octopus', k:'telescope', c1:'#e2eef2', clear:true} },
  { id:'barreleye', name:'Barreleye', sci:'Macropinna microstoma', wiki:'Barreleye', group:'Fish', m:650, range:[600,800], hab:'open', cm:15, diet:'Jellies & small animals',
    fact:'Its head is a clear, fluid-filled dome, and its green tube eyes rotate to look up through it.', art:{t:'fish', k:'barreleye', c1:'#4c5960', c2:'#8a979d', tail:'round', h:.32} },
  { id:'oarfish', name:'Giant oarfish', sci:'Regalecus glesne', wiki:'Giant_oarfish', group:'Fish', m:300, range:[20,1000], hab:'open', cm:800, diet:'Krill & small squid',
    fact:'The longest bony fish, reaching 8 m or more. It may lie behind old sea-serpent legends.', art:{t:'eel', k:'oar', c1:'#c9ced2', c2:'#e04a4a'} },
  { id:'opah', name:'Opah', sci:'Lampris guttatus', wiki:'Opah', group:'Fish', m:250, range:[50,500], hab:'open', cm:200, diet:'Squid & fish',
    fact:'The first fish found to be fully warm-blooded, circulating heated blood around its body.', art:{t:'fish', c1:'#b04a5a', c2:'#e0703a', pattern:'spots', tail:'fork', h:.7} },
  { id:'swordfish', name:'Swordfish', sci:'Xiphias gladius', wiki:'Swordfish', group:'Fish', m:350, range:[0,800], nightM:40, hab:'open', cm:450, diet:'Fish & squid',
    fact:'A special organ warms its eyes and brain, helping it see clearly in cold, deep water.', art:{t:'fish', c1:'#2e3a52', c2:'#b9c2cc', bill:true, tail:'lunate', h:.22} },
  { id:'megamouth', name:'Megamouth shark', sci:'Megachasma pelagios', wiki:'Megamouth_shark', group:'Shark & ray', m:250, range:[0,1000], nightM:25, hab:'open', cm:550, diet:'Krill & plankton',
    fact:'Not discovered until 1976. It rises toward the surface at night to filter-feed.', art:{t:'shark', k:'megamouth', c1:'#4a4a52', c2:'#9a9aa2'} },
  { id:'sixgill', name:'Bluntnose sixgill shark', sci:'Hexanchus griseus', wiki:'Bluntnose_sixgill_shark', group:'Shark & ray', m:500, range:[0,2500], hab:'open', cm:480, diet:'Fish, seals & carrion',
    fact:'Has six pairs of gill slits, one more than most sharks, a sign of a very ancient family.', art:{t:'shark', c1:'#5a5348', c2:'#9a9182', eye:1.4} },
  { id:'goblin-shark', name:'Goblin shark', sci:'Mitsukurina owstoni', wiki:'Goblin_shark', group:'Shark & ray', m:800, range:[0,1300], hab:'slope', cm:380, diet:'Fish, squid & crustaceans',
    fact:'Can fling its jaws forward out of its mouth to snatch prey.', art:{t:'shark', k:'goblin', c1:'#d3a2a2', c2:'#e8c8c4'} },
  { id:'frilled-shark', name:'Frilled shark', sci:'Chlamydoselachus anguineus', wiki:'Frilled_shark', group:'Shark & ray', m:950, range:[50,1500], hab:'slope', cm:200, diet:'Squid & fish',
    fact:'An ancient-looking shark with around 300 needle-like teeth arranged in rows.', art:{t:'eel', k:'frill', c1:'#5b4a44', c2:'#8a766c'} },
  { id:'cookiecutter', name:'Cookiecutter shark', sci:'Isistius brasiliensis', wiki:'Cookiecutter_shark', group:'Shark & ray', m:900, range:[0,3700], nightM:100, hab:'open', cm:50, glow:true, diet:'Plugs of flesh',
    fact:"Bites round plugs out of whales, tuna and even the rubber coating of submarines' sonar domes.", art:{t:'shark', k:'cookie', c1:'#6a5a4e', c2:'#a08f80'} },
  { id:'siphonophore', name:'Giant siphonophore', sci:'Praya dubia', wiki:'Praya_dubia', group:'Cnidarian', m:800, range:[300,1000], hab:'open', cm:4000, glow:true, diet:'Small crustaceans & fish',
    fact:'A colony of linked individuals that can stretch more than 40 m, one of the longest animals on Earth.', art:{t:'siphon', c1:'#d9e8ff', c2:'#ffb08a'} },
  { id:'pyrosome', name:'Pyrosome', sci:'Pyrosoma atlanticum', wiki:'Pyrosoma_atlanticum', group:'Tunicate', m:400, range:[0,800], nightM:40, hab:'open', cm:60, glow:true, diet:'Phytoplankton',
    fact:'A glowing tube made of thousands of clones. Touch it and waves of light ripple along its body.', art:{t:'pyrosome', c1:'#f2c9d6'} },
  { id:'larvacean', name:'Giant larvacean', sci:'Bathochordaeus', wiki:'Bathochordaeus', group:'Tunicate', m:300, range:[100,500], hab:'open', cm:100, diet:'Marine snow & plankton',
    fact:"Builds a mucus 'house' up to 1 m wide to filter food, then abandons it and builds a new one.", art:{t:'larvacean', c1:'#e8eef0', c2:'#c25a3a'} },
  { id:'bloodybelly', name:'Bloody-belly comb jelly', sci:'Lampocteis cruentiventer', wiki:'Lampocteis', group:'Comb jelly', m:700, range:[300,1200], hab:'open', cm:16, glow:true, diet:'Small crustaceans',
    fact:'Its red gut hides the glow of the prey it has eaten, so it stays invisible in the dark.', art:{t:'comb', k:'red', c1:'#c2283e'} },

  // ---------------- MIDNIGHT ZONE ----------------
  { id:'greenland-shark', name:'Greenland shark', sci:'Somniosus microcephalus', wiki:'Greenland_shark', group:'Shark & ray', m:1200, range:[0,2200], hab:'open', cm:640, diet:'Fish, seals & carrion',
    fact:'The longest-living vertebrate known. Some are estimated to be several hundred years old.', art:{t:'shark', k:'sleeper', c1:'#58605e', c2:'#868d8a'} },
  { id:'viperfish', name:"Sloane's viperfish", sci:'Chauliodus sloani', wiki:"Sloane's_viperfish", group:'Fish', m:1100, range:[200,2800], nightM:400, hab:'open', cm:35, glow:true, diet:'Fish & crustaceans',
    fact:"Its needle-like teeth are so long they don't fit inside its mouth.", art:{t:'fish', k:'viper', c1:'#20343c', c2:'#3f5964', teeth:true, photo:'belly', tail:'fork', h:.16} },
  { id:'loosejaw', name:'Stoplight loosejaw', sci:'Malacosteus niger', wiki:'Malacosteus_niger', group:'Fish', m:1300, range:[500,4000], hab:'open', cm:25, glow:true, diet:'Copepods & shrimp',
    fact:'Makes red light that most deep-sea animals cannot see, like a secret spotlight.', art:{t:'fish', k:'loosejaw', c1:'#141218', c2:'#2a2530', teeth:true, tail:'fork', h:.2} },
  { id:'snipe-eel', name:'Slender snipe eel', sci:'Nemichthys scolopaceus', wiki:'Slender_snipe_eel', group:'Fish', m:1100, range:[300,2000], hab:'open', cm:130, diet:'Shrimp',
    fact:"Its long, beak-like jaws curve apart and can't fully close.", art:{t:'eel', k:'snipe', c1:'#5a4a3a', c2:'#8a7a62'} },
  { id:'fangtooth', name:'Common fangtooth', sci:'Anoplogaster cornuta', wiki:'Anoplogaster_cornuta', group:'Fish', m:1600, range:[500,5000], hab:'open', cm:16, diet:'Fish & shrimp',
    fact:'Has the largest teeth for its body size of any fish in the ocean.', art:{t:'fish', k:'fang', c1:'#2a1f1d', c2:'#5a4440', teeth:true, tail:'round', h:.5} },
  { id:'black-swallower', name:'Black swallower', sci:'Chiasmodon niger', wiki:'Black_swallower', group:'Fish', m:1500, range:[700,2750], hab:'open', cm:25, diet:'Fish',
    fact:'Can swallow fish more than twice its own length, thanks to a hugely stretchy stomach.', art:{t:'fish', k:'swallower', c1:'#1f1e22', c2:'#3a3840', tail:'fork', h:.22} },
  { id:'anglerfish', name:'Humpback anglerfish', sci:'Melanocetus johnsonii', wiki:'Melanocetus_johnsonii', group:'Fish', m:1800, range:[100,4500], hab:'open', cm:18, glow:true, diet:'Fish & shrimp',
    fact:'Its lure glows because of bacteria living inside it.', art:{t:'angler', c1:'#2e2622', c2:'#4a3e38'} },
  { id:'gulper', name:'Gulper eel', sci:'Eurypharynx pelecanoides', wiki:'Pelican_eel', group:'Fish', m:2200, range:[500,3000], hab:'open', cm:100, glow:true, diet:'Crustaceans & small fish',
    fact:'Its loose jaws open wide enough to swallow prey almost as big as itself.', art:{t:'eel', k:'gulper', c1:'#211d29', c2:'#3a3446'} },
  { id:'helmet-jelly', name:'Helmet jellyfish', sci:'Periphylla periphylla', wiki:'Periphylla_periphylla', group:'Cnidarian', m:1250, range:[0,7000], hab:'open', cm:20, glow:true, diet:'Krill & small fish',
    fact:'Sensitive to light, it avoids the sunlit water and rises only in darkness.', art:{t:'jelly', k:'helmet', c1:'#7a1f2e', c2:'#c25a6a'} },
  { id:'big-red', name:'Big red jellyfish', sci:'Tiburonia granrojo', wiki:'Tiburonia_granrojo', group:'Cnidarian', m:1100, range:[600,1500], hab:'open', cm:75, diet:'Unknown',
    fact:'Has no stinging tentacles. It uses four to seven thick, fleshy arms instead.', art:{t:'jelly', k:'bigred', c1:'#a8162c', c2:'#d24a5a'} },
  { id:'deepstaria', name:'Deepstaria', sci:'Deepstaria enigmatica', wiki:'Deepstaria', group:'Cnidarian', m:1500, range:[600,1750], hab:'open', cm:60, diet:'Small animals',
    fact:'Its thin bell spreads like a sheet and wraps around prey like a bag.', art:{t:'jelly', k:'deepstaria', c1:'#e8d9b8', c2:'#c9b48d'} },
  { id:'colossal-squid', name:'Colossal squid', sci:'Mesonychoteuthis hamiltoni', wiki:'Colossal_squid', group:'Mollusc', m:2000, range:[1000,2200], hab:'open', cm:1000, glow:true, diet:'Fish & squid',
    fact:'The heaviest invertebrate known, with the largest eyes ever measured in any animal.', art:{t:'squid', k:'colossal', c1:'#a8382a', c2:'#d8705a'} },
  { id:'unicumber', name:'Swimming sea cucumber', sci:'Enypniastes eximia', wiki:'Enypniastes', group:'Echinoderm', m:2500, range:[500,5000], hab:'open', cm:25, glow:true, diet:'Seafloor sediment',
    fact:"A sea cucumber that swims and glows. Its nickname is the 'headless chicken monster'.", art:{t:'cucumber', k:'swim', c1:'#e66a7a', c2:'#f6b0b8', clear:true} },
  { id:'atolla', name:'Atolla jellyfish', sci:'Atolla wyvillei', wiki:'Atolla_jellyfish', group:'Cnidarian', m:2600, range:[500,4000], hab:'open', cm:17, glow:true, diet:'Small crustaceans',
    fact:"When attacked it flashes a spinning ring of blue light, a 'burglar alarm' that may summon a bigger predator.", art:{t:'jelly', k:'atolla', c1:'#a3263a', c2:'#d65a6a'} },
  { id:'bigfin-squid', name:'Bigfin squid', sci:'Magnapinna', wiki:'Bigfin_squid', group:'Mollusc', m:3000, range:[1900,6200], hab:'open', cm:800, diet:'Unknown',
    fact:"Its arms bend sharply at 'elbows' and trail for several metres below it.", art:{t:'squid', k:'bigfin', c1:'#d9c8bd', c2:'#b29a8a'} },
  { id:'isopod', name:'Giant isopod', sci:'Bathynomus giganteus', wiki:'Bathynomus_giganteus', group:'Crustacean', m:1300, range:[170,2140], hab:'slope', benthic:true, cm:50, diet:'Carrion',
    fact:'A giant relative of woodlice that can survive for very long periods without eating.', art:{t:'shrimp', k:'isopod', c1:'#c7bba8', c2:'#9d907c'} },
  { id:'lizardfish', name:'Deep-sea lizardfish', sci:'Bathysaurus ferox', wiki:'Bathysaurus_ferox', group:'Fish', m:2400, range:[600,3500], hab:'slope', benthic:true, cm:65, diet:'Fish',
    fact:'A top predator of the deep seafloor that lies in wait with a mouth full of hooked teeth.', art:{t:'fish', c1:'#4f4a42', c2:'#7d756a', teeth:true, head:'flat', tail:'fork', h:.16} },
  { id:'harp-sponge', name:'Harp sponge', sci:'Chondrocladia lyra', wiki:'Chondrocladia_lyra', group:'Sponge', m:3100, range:[3300,3500], hab:'slope', benthic:true, cm:37, diet:'Tiny crustaceans',
    fact:'A meat-eating sponge that snares tiny crustaceans on its harp-shaped branches.', art:{t:'sponge', k:'harp', c1:'#e8dcc4', c2:'#f6efe0'} },

  // hydrothermal vents, whale fall
  { id:'tube-worm', name:'Giant tube worm', sci:'Riftia pachyptila', wiki:'Riftia_pachyptila', group:'Worm', m:2550, range:[1500,3000], hab:'vent', benthic:true, cm:200, school:3, diet:'Chemicals via bacteria',
    fact:'Has no mouth or gut. Bacteria living inside it turn chemicals from the vent into food.', art:{t:'worm', k:'tube', c1:'#e8e2d6', c2:'#d8233a'} },
  { id:'yeti-crab', name:'Yeti crab', sci:'Kiwa hirsuta', wiki:'Kiwa_hirsuta', group:'Crustacean', m:2550, range:[2200,2300], hab:'vent', benthic:true, cm:15, diet:'Bacteria',
    fact:'Grows bacteria on its hairy arms, possibly to eat them.', art:{t:'crab', k:'yeti', c1:'#efe8dc', c2:'#d8cfbf'} },
  { id:'scaly-foot', name:'Scaly-foot snail', sci:'Chrysomallon squamiferum', wiki:'Chrysomallon_squamiferum', group:'Mollusc', m:2600, range:[2400,2900], hab:'vent', benthic:true, cm:4.5, diet:'Chemicals via bacteria',
    fact:'Builds armour plates out of iron sulphide, the only animal known to do so.', art:{t:'snail', k:'scaly', c1:'#2a2a2e', c2:'#6a6a70'} },
  { id:'pompeii-worm', name:'Pompeii worm', sci:'Alvinella pompejana', wiki:'Pompeii_worm', group:'Worm', m:2550, range:[2000,3000], hab:'vent', benthic:true, cm:12, diet:'Bacteria',
    fact:'Lives in tubes on scalding vent chimneys and is among the most heat-tolerant animals known.', art:{t:'worm', k:'pompeii', c1:'#d8c0a8', c2:'#d8233a'} },
  { id:'vent-shrimp', name:'Vent shrimp', sci:'Rimicaris exoculata', wiki:'Rimicaris_exoculata', group:'Crustacean', m:2600, range:[1600,4000], hab:'vent', benthic:true, cm:6, school:5, diet:'Bacteria',
    fact:'Has no normal eyes but a light-sensitive patch on its back that may detect the faint glow of vents.', art:{t:'shrimp', c1:'#e8d4c4'} },
  { id:'zombie-worm', name:'Zombie worm', sci:'Osedax', wiki:'Osedax', group:'Worm', m:3100, range:[25,4000], hab:'whalefall', benthic:true, cm:6, school:4, diet:'Whale bones',
    fact:'Has no mouth or gut. It feeds on whale bones using root-like tissue and bacteria.', art:{t:'worm', k:'zombie', c1:'#d8233a', c2:'#f2b0b0'} },

  // ---------------- THE ABYSS ----------------
  { id:'dumbo', name:'Dumbo octopus', sci:'Grimpoteuthis', wiki:'Grimpoteuthis', group:'Mollusc', m:4100, range:[1000,7000], hab:'open', cm:30, diet:'Worms & crustaceans',
    fact:'Flaps ear-like fins to swim. These are the deepest-living octopuses known, found near 7,000 m.', art:{t:'octopus', k:'dumbo', c1:'#e59a8a', c2:'#f6c8b8'} },
  { id:'sea-spider', name:'Giant sea spider', sci:'Colossendeis', wiki:'Colossendeis', group:'Other', m:3900, range:[500,5000], hab:'plain', benthic:true, cm:70, diet:'Soft animals',
    fact:'Its body is so small that its gut runs down into its long legs.', art:{t:'seaspider', c1:'#e07a3a'} },
  { id:'tripod-fish', name:'Tripod fish', sci:'Bathypterois grallator', wiki:'Bathypterois_grallator', group:'Fish', m:4300, range:[870,4720], hab:'plain', benthic:true, cm:37, diet:'Small crustaceans',
    fact:'Stands on three stiff fin rays above the seafloor, facing into the current to catch passing prey.', art:{t:'fish', k:'tripod', c1:'#6a6f72', c2:'#9aa0a3', tail:'fork', h:.18} },
  { id:'sea-pig', name:'Sea pig', sci:'Scotoplanes', wiki:'Scotoplanes', group:'Echinoderm', m:4500, range:[1000,6000], hab:'plain', benthic:true, cm:15, school:4, diet:'Seafloor mud',
    fact:'A sea cucumber that walks on tube feet, sifting the abyssal mud for food.', art:{t:'cucumber', k:'pig', c1:'#e8b8c0', c2:'#f6d6da', clear:true} },
  { id:'brittle-star', name:'Brittle star', sci:'Ophiuroidea', wiki:'Brittle_star', group:'Echinoderm', m:4600, range:[0,8000], hab:'plain', benthic:true, cm:20, school:3, diet:'Detritus & plankton',
    fact:'Can regrow lost arms. In places, brittle stars carpet the deep seafloor by the millions.', art:{t:'star', k:'brittle', c1:'#d8c0a0'} },
  { id:'grenadier', name:'Abyssal grenadier', sci:'Coryphaenoides armatus', wiki:'Coryphaenoides_armatus', group:'Fish', m:4800, range:[2000,5180], hab:'plain', cm:100, diet:'Carrion & small animals',
    fact:'A rattail scavenger that quickly finds food falling from far above.', art:{t:'fish', c1:'#8c8577', c2:'#b8b1a2', tail:'rat', eye:1.4, h:.3} },
  { id:'faceless-cusk', name:'Faceless cusk', sci:'Typhlonus nasus', wiki:'Typhlonus_nasus', group:'Fish', m:4200, range:[3900,5100], hab:'plain', benthic:true, cm:30, diet:'Small animals',
    fact:'Has no visible eyes. It was rediscovered in 2017, more than a century after it was first collected.', art:{t:'fish', c1:'#c9b5a0', c2:'#e2d4c4', tail:'rat', eye:0, h:.3} },
  { id:'cusk-eel', name:'Abyssal cusk-eel', sci:'Abyssobrotula galatheae', wiki:'Abyssobrotula_galatheae', group:'Fish', m:5600, range:[3110,8370], hab:'trench', cm:16, diet:'Small invertebrates',
    fact:'Once held the record for the deepest fish ever caught, hauled up from 8,370 m.', art:{t:'fish', c1:'#d8c4b0', c2:'#efe2d4', tail:'rat', eye:.6, h:.22} },

  // ---------------- HADAL ZONE ----------------
  { id:'xenophyophore', name:'Xenophyophore', sci:'Xenophyophorea', wiki:'Xenophyophorea', group:'Other', m:7200, range:[500,10600], hab:'trench', benthic:true, cm:20, school:2, diet:'Particles & bacteria',
    fact:'A single cell that can grow as big as a grapefruit.', art:{t:'blob', c1:'#c9b48d', c2:'#a08a64'} },
  { id:'snailfish', name:'Hadal snailfish', sci:'Pseudoliparis swirei', wiki:'Mariana_snailfish', group:'Fish', m:7900, range:[6900,8200], hab:'trench', cm:30, school:2, diet:'Amphipods',
    fact:'A snailfish filmed at 8,336 m in 2022 is the deepest fish ever recorded.', art:{t:'fish', k:'snail', c1:'#f0c5c7', c2:'#f9e2e3', clear:true, tail:'rat', h:.36} },
  { id:'amphipod', name:'Supergiant amphipod', sci:'Hirondellea gigas', wiki:'Amphipoda', group:'Crustacean', m:10850, range:[6000,10900], hab:'trench', benthic:true, cm:5, school:5, diet:'Sunken wood & carrion',
    fact:'Lives at the bottom of the Challenger Deep and makes enzymes that can digest wood sinking from land.', art:{t:'shrimp', k:'amphipod', c1:'#eadccb'} },
];

// Landmarks are places, not species. Discovered by swimming close.
export const LANDMARKS = [
  { id:'seagrass', name:'Seagrass meadow', x:-1710, m:5, fact:'Seagrass meadows store carbon far faster than rainforests and shelter young fish.' },
  { id:'reef', name:'Coral reef', x:-1560, m:16, fact:'Coral reefs cover under 1% of the seafloor yet support about a quarter of all marine species.' },
  { id:'kelp', name:'Kelp forest', x:-1380, m:32, fact:'Kelp is a giant alga, not a plant. Its forests are some of the most productive habitats on Earth.' },
  { id:'whalefall', name:'Whale fall', x:-770, m:3100, fact:'A sunken whale can feed a whole community of deep-sea life for decades.' },
  { id:'wreck', name:'Shipwreck', x:-520, m:3950, fact:'Cold, dark water preserves wrecks for a long time. RMS Titanic lies near 3,800 m.' },
  { id:'vents', name:'Black smoker field', x:1320, m:2520, fact:'Hydrothermal vents can blast out water hotter than 350 °C, yet life thrives around them on chemical energy.' },
  { id:'plain', name:'Abyssal plain', x:560, m:4780, fact:'Abyssal plains are among the flattest places on Earth and cover about half of the planet.' },
  { id:'challenger', name:'Challenger Deep', x:0, m:10935, fact:'The deepest known point in the ocean. Fewer people have been here than have been to space.' },
];
